echo YOUTUBECLIENTID=\'$YOUTUBECLIENTID\' >> config.env
echo YOUTUBECLIENTSECRET=\'$YOUTUBECLIENTSECRET\' >> config.env
echo SPOTIFYCLIENTID=\'$SPOTIFYCLIENTID\' >> config.env
echo SPOTIFYCLIENTSECRET=\'$SPOTIFYCLIENTSECRET\' >> config.env
echo LASTFMAPIKEY=\'$LASTFMAPIKEY\' >> config.env
echo LASTFMSECRET=\'$LASTFMSECRET\' >> config.env
echo FANARTTVAPIKEY=\'$FANARTTVAPIKEY\' >> config.env
echo $(ls)